# Generated by Django 4.1 on 2022-12-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_time', models.CharField(max_length=50)),
                ('reply_time', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('num_reply', models.IntegerField(default=0)),
                ('num_respond', models.IntegerField(default=0)),
                ('num_star', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('responded_rid', models.IntegerField(default=-1)),
                ('content', models.CharField(max_length=300)),
                ('created_time', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bbs')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('created_time', models.CharField(max_length=50)),
                ('num_followed', models.IntegerField(default=0)),
                ('num_follow', models.IntegerField(default=0)),
                ('follow', models.ManyToManyField(related_name='followed', to='app.user')),
                ('post', models.ManyToManyField(related_name='posted', to='app.bbs')),
                ('reply', models.ManyToManyField(related_name='replied', to='app.respond')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bbs')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='respond',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='bbs',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
