# Generated by Django 4.1 on 2022-12-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.ManyToManyField(related_name='stared', to='app.bbs'),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
