# Generated by Django 4.1 on 2022-12-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuid', to='app.user')),
                ('to_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuid', to='app.user')),
            ],
        ),
    ]
