# Generated by Django 4.1 on 2022-12-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_star_delete_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbs',
            old_name='num_respond',
            new_name='num_seen',
        ),
    ]
