# Generated by Django 4.1 on 2022-12-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='star',
        ),
    ]
