# Generated by Django 4.1 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_num_respond_bbs_num_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='uname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
