# Generated by Django 4.1 on 2022-12-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bbs_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='num_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='app.bbs'),
        ),
    ]
