# Generated by Django 4.1 on 2022-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bbs_num_like_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='uname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
