# Generated by Django 4.1 on 2022-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_respond_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respond',
            name='responded_rid',
        ),
        migrations.AddField(
            model_name='respond',
            name='rename',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
